### ISSUE TITLE
add dependency on epel

### ISSUE THREAD

**Issue by dirks** [geerlingguy/ansible-role-repo-remi#15]
According to [remirepo.net](https://blog.remirepo.net/pages/Config-en) the repo has the following requirements:

- Fedora : RPM Fusion
- RHEL : Optional and EPEL
- CentOS : EPEL

Should those not be listed in the readme as requirements? One could also add role dependencies in meta/main, but that would be requirements on specific roles. Maybe someone is not using your epel role yet. ;)

**Comment by devantoine** [comment]
Ahah, I just stumbled this issue, trying to enable remirepo on RHEL7 and getting an error.
