### ISSUE TITLE
Install remi repo

### ISSUE THREAD

**Issue by Loganguy** [geerlingguy/ansible-role-repo-remi#18]
Ubuntu 18.04
virtualbox 5.2.34
Vagrant 2.2.3
ansible 2.8.0
composer 1.9.1
I am running centos7 guest on ubuntu 18.04.  I'm getting  

TASK [geerlingguy.repo-remi : Install remi repo.] ******************************
fatal: [oppsvm]: FAILED! => {"changed": false, "msg": "Failure downloading http://rpms.remirepo.net/enterprise/remi-release-7.rpm, Request failed: <urlopen error [Errno -2] Name or service not known>"}
The same vagrant box works fine on mac os catalina.

Thanks
Milton

**Comment by geerlingguy** [comment]
Sometimes it is just an HTTP error, it happens on my CI builds from time to time. Other than that it could be networking having issues (does DNS work inside that particular VM (try with `vagrant ssh` then ping or dig a URL)?).
