### ISSUE TITLE
Task ordering can cause gpg checking errors

### ISSUE THREAD

**Issue by GitBytes** [geerlingguy/ansible-role-repo-remi#23]
In our deployment to RHEL8, we encountered some issues around the GPG Key validation. It seems to be solved by reversing the order of the tasks in `main.yml`. I will submit a pull request to have you review the issue @geerlingguy.

**Comment by GitBytes** [comment]
This is in relation to DrupalVM actually. Didn't realize the version of repo-remi was as out of date on master as it is. This bug has been fixed in the newer versions of this role. Would you like me to file an issue with the DrupalVM repo instead?

**Comment by GitBytes** [comment]
At this time I think it best to make you aware of the new issue I filed on DrupalVM and hold off on submitting a pull request to hold for any feedback. I am guessing there may be a good reason this was delayed. Cheers!

**Comment by geerlingguy** [comment]
I've fixed it in the Drupal VM repo in the issue you linked. Other issue #22 is related but not the same, so I'll leave that open.
