### ISSUE TITLE
5.6 and other repositories?

### ISSUE THREAD

**Issue by strarsis** [geerlingguy/ansible-role-repo-remi#28]
@geerlingguy: 
Can this role also add other remi-PHP-repositories, like `Remi's PHP 5.6 RPM repository for Enterprise Linux 7 - x86_64` ?

**Comment by geerlingguy** [comment]
@strarsis - Technically it might be able to, but I don't offer any kind of support for ancient / completely unsupported versions of PHP anymore, so to get it working you'd be on your own.

**Comment by strarsis** [comment]
@geerlingguy: Interestingly the PHP 5.6 repository is also added with this role, apparently the `releases` file does this.
I can directly install PHP 5.6 from remi repository, explicitly adding the 5.6 repository even causes an error (duplicate repository).
