### ISSUE TITLE
Would be niece to have variable to pick PHP version

### ISSUE THREAD

**Issue by krisdante** [geerlingguy/ansible-role-repo-remi#4]
Remi supports multiple versions of PHP. Now only default one will be used.

**Comment by ynott** [comment]
uhmm.
Yes, remi repos has a multiple versions.
But, you need to install only one of the remi-release-{{ ansible_distribution_major_version }}.rpm.
This package installed three files.
remi-php70.repo
remi-safe.repo
remi.repo

If you want to install PHP for the specified version , Please specify the repository name.
(e.g. remi-php55, remi-php56, remi-php70)

**Comment by geerlingguy** [comment]
@ynott is correct; see how this is done with Drupal VM here: https://github.com/geerlingguy/drupal-vm/blob/06ec267fb71534a9fa2cd5ca1cee51615d596363/provisioning/tasks/init-redhat.yml#L12-L22
