### ISSUE TITLE
Failure downloading http://rpms.remirepo.net/enterprise/remi-release-7.rpm

### ISSUE THREAD

**Issue by McFateM** [geerlingguy/ansible-role-repo-remi#7]
I'm getting this error (full text provided below) when trying to 'vagrant up' any/all drupal-vm instances I have today.  I've tried this with different versions of VirtualBox and Vagrant on different hosts, and with both old and new clones of drupal-vm/master with the same result in all cases thus far. 

The host I am currently working from has all new VB and Vagrant so I'm going to try a couple of things...like switching from CentOS to Ubuntu, and cloning drupal-vm/master without modification and trying to get something up and running.

FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading http://rpms.remirepo.net/enterprise/remi-release-7.rpm, [Errno 104] Connection reset by peer"}

**Comment by geerlingguy** [comment]
@McFateM - Can you try the troubleshooting steps here? https://github.com/geerlingguy/drupal-vm/issues/850#issuecomment-237874597

It might just be a networking issue.

**Comment by McFateM** [comment]
I'll check it out and give it a go when I have a little time.  I'm currently outfitting a spare MacBook Air with Sierra and all of the working parts mentioned in https://github.com/geerlingguy/drupal-vm/issues/981.  Thanks and take care.

-Mark M.

**Comment by McFateM** [comment]
Actually I was having issues with https://github.com/geerlingguy/drupal-vm/issues/981 and rolling back to VirtualBox 5.1.6 and pulling your updates from a couple of weeks ago got me past both issues.  Thanks.
